ARG UV_VERSION=latest

FROM ghcr.io/astral-sh/uv:$UV_VERSION AS uv


FROM python:3.13-slim-bullseye

# 環境変数の設定
ENV UV_PROJECT_ENVIRONMENT='/usr/local/'
ENV UV_SYSTEM_PYTHON=1
ENV APP_BASE_DIR=/opt

# バージョンを指定してuvをコピー
COPY --from=uv /uv /bin/uv

WORKDIR /opt


# Copy the entire repository so that source and test files are available
COPY . /opt

# Synchronize uv if required
RUN uv sync

CMD [ "uv", "run", "pytest", "-n", "auto", "-s" ]
