ARG UV_VERSION=latest

FROM ghcr.io/astral-sh/uv:$UV_VERSION AS uv


FROM mcr.microsoft.com/vscode/devcontainers/python:3.13

# コンテナ内に.venvを作らないようにする環境変数
ENV UV_PROJECT_ENVIRONMENT='/usr/local/'
ENV UV_SYSTEM_PYTHON=1

# バージョンを指定してuvをコピー
COPY --from=uv /uv /bin/uv

WORKDIR /opt


# Copy the entire repository so that source and test files are available
COPY . /opt

# Synchronize uv if required
RUN uv sync

