version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - app-data:/app/downloads
      - app-logs:/app/log
      - app-outputs:/app/outputs
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SPREADSHEET_KEY=${SPREADSHEET_KEY}
    tty: true
    stdin_open: true
    command: /bin/sh

volumes:
  app-data:
  app-logs:
  app-outputs:
