[project]
name = "default"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "kyouyap" }
]
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "gspread-dataframe>=4.0.0",
    "python-dotenv>=1.0.1",
    "selenium>=4.30.0",
    "oauth2client>=4.1.3",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
]

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "gspread_dataframe"
ignore_missing_imports = true

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
    "pre-commit>=3.8.0",
    "ruff>=0.6.3",
    "mypy>=1.15.0",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-skip-slow>=0.0.5",
    "pytest-subtests>=0.14.1",
    "coverage>=7.6.12",
    "types-aiofiles>=24.1.0.20241221",
    "pandas-stubs>=2.2.3.250308",
    "types-pyyaml>=6.0.12.20241230",
]
