version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: "/app/log/app.log"
    maxBytes: 5242880  # 5MB
    backupCount: 5
    encoding: "utf-8"
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

loggers:
  src:
    level: INFO
    handlers: [file, console]
    propagate: false

  src.scraper:
    level: INFO
    handlers: [file, console]
    propagate: false

  src.spreadsheet:
    level: INFO
    handlers: [file, console]
    propagate: false

root:
  level: INFO
  handlers: [file, console]
