---
version: 1
disable_existing_loggers: false
level: INFO

formatters:
  json:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: colored
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: log/app.log
    maxBytes: 5242880  # 5MB
    backupCount: 5
    encoding: utf-8

loggers:
  "":  # rootロガー
    level: INFO
    handlers: [console, file]
    propagate: true

  selenium:  # Selenium関連のログ
    level: INFO
    handlers: [console, file]
    propagate: false

  urllib3:  # HTTP関連のログ
    level: WARNING
    handlers: [console]
    propagate: false
