name: Mypy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }} with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run mypy
        run: uv run mypy .
