name: Run Tests and Static Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-app:latest .

    - name: Run tests in Docker container
      run: |
        docker run --rm -e PYTHONPATH=src my-app:latest pytest /app/test/

    - name: Run mypy in Docker container
      run: |
        docker run --rm my-app:latest mypy /app/src /app/test/

    - name: Run ruff in Docker container
      run: |
        docker run --rm my-app:latest ruff check /app/src /app/test/
